### ISSUE TITLE
test failing in xest

### ISSUE THREAD

**Issue by asmodehn** [asmodehn/xest#20]
```
Error: .....18:50:11.199 [error] GenServer Xest.APIServer.Test.TestServer terminating
Warning: ** (UndefinedFunctionError) function nil.utc_now/0 is undefined
    nil.utc_now()
    (xest 0.1.0) lib/xest/transient_map.ex:49: Xest.TransientMap.dead_or_alive/1
Warning:     (xest 0.1.0) lib/xest/transient_map.ex:39: Xest.TransientMap.fetch/2
    lib/xest/api_server.ex:44: Xest.APIServer.Test.TestServer.handle_call/3
Warning:     (stdlib 3.16.1) gen_server.erl:721: :gen_server.try_handle_call/4
    (stdlib 3.16.1) gen_server.erl:750: :gen_server.handle_msg/6
Warning:     (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.9562.0>): {:some_request, "some_param"}


  1) test Given time to cache call cache the result for a while (Xest.APIServer.Test)
Error:      apps/xest/test/xest/api_server_test.exs:82
     ** (exit) exited in: GenServer.call(#PID<0.9565.0>, {:some_request, "some_param"}, 5000)
         ** (EXIT) an exception was raised:
             ** (UndefinedFunctionError) function nil.utc_now/0 is undefined
                 nil.utc_now()
                 (xest 0.1.0) lib/xest/transient_map.ex:49: Xest.TransientMap.dead_or_alive/1
Warning:                  (xest 0.1.0) lib/xest/transient_map.ex:39: Xest.TransientMap.fetch/2
                 lib/xest/api_server.ex:44: Xest.APIServer.Test.TestServer.handle_call/3
Warning:                  (stdlib 3.16.1) gen_server.erl:721: :gen_server.try_handle_call/4
                 (stdlib 3.16.1) gen_server.erl:750: :gen_server.handle_msg/6
Warning:                  (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
     code: state_as_response = APIServer.call(server_pid, {:some_request, "some_param"})
     stacktrace:
       (elixir 1.11.4) lib/gen_server.ex:1027: GenServer.call/3
Warning:        test/xest/api_server_test.exs:90: (test)
```

**Comment by asmodehn** [comment]
Happened there : https://github.com/asmodehn/xest/runs/4127121793?check_suite_focus=true

**Comment by asmodehn** [comment]
It is unclear why this happens... In any case someone could review the clock & cache implementation when time permits, to suggest a better/simpler approach...

**Comment by asmodehn** [comment]
This seems to have been fixed.
It likely was because of an `async: true` while an app-wide setting was replaced by a mock...
